-- Tables for Volunteer Applications and Partnership Requests

-- 1. Volunteer Applications Table
CREATE TABLE IF NOT EXISTS public.volunteer_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    interest_area TEXT NOT NULL,
    motivation TEXT,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'reviewed', 'accepted', 'rejected')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Partnership Requests Table
CREATE TABLE IF NOT EXISTS public.partnership_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    organization_name TEXT NOT NULL,
    contact_email TEXT NOT NULL,
    mission_alignment TEXT,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'reviewed', 'contacted')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Donations Table (to track successful donations)
CREATE TABLE IF NOT EXISTS public.donations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    amount DECIMAL(10, 2) NOT NULL,
    currency TEXT DEFAULT 'USD',
    payment_method TEXT NOT NULL, -- 'paypal', 'card', 'mpesa'
    payment_status TEXT DEFAULT 'completed',
    project_id BIGINT REFERENCES public.activities(id) ON DELETE SET NULL, -- Optional if for a specific project
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.volunteer_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.partnership_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donations ENABLE ROW LEVEL SECURITY;

-- Policies
-- Anyone can insert (for anonymous leads), but only admins can view
CREATE POLICY "Anyone can submit volunteer applications" ON public.volunteer_applications FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins can view volunteer applications" ON public.volunteer_applications FOR SELECT TO authenticated USING ( public.is_admin() );

CREATE POLICY "Anyone can submit partnership requests" ON public.partnership_requests FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins can view partnership requests" ON public.partnership_requests FOR SELECT TO authenticated USING ( public.is_admin() );

CREATE POLICY "Anyone can record donations" ON public.donations FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can view own donations" ON public.donations FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Admins can view all donations" ON public.donations FOR SELECT TO authenticated USING ( public.is_admin() );
