-- Supabase Schema for Oasis of Hope Website
-- Paste this into your Supabase SQL Editor

-- 1. Create Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    username TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    bio TEXT,
    role TEXT DEFAULT 'community' CHECK (role IN ('community', 'admin', 'volunteer')),
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    avatar_url TEXT DEFAULT 'assets/images/hero/logo.png',
    phone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Activities Table (Community Posts)
CREATE TABLE IF NOT EXISTS public.activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    text TEXT NOT NULL,
    media_url TEXT,
    media_type TEXT DEFAULT 'none' CHECK (media_type IN ('none', 'image', 'video')),
    tag TEXT DEFAULT 'Community',
    likes_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Enable RLS (Row Level Security)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies for Profiles
-- Allow any user to see all profiles (for usernames and avatars in feed)
CREATE POLICY "Public profiles are viewable by everyone" 
ON public.profiles FOR SELECT USING (true);

-- Allow users to insert their own profile upon registration
CREATE POLICY "Users can insert their own profile" 
ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- Allow users to update their own basic info (except role and status)
CREATE POLICY "Users can update own profile" 
ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- SECURITY DEFINER function to break recursion in RLS
CREATE OR REPLACE FUNCTION public.is_admin() 
RETURNS boolean AS $$
    SELECT EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE id = auth.uid() AND role = 'admin'
    );
$$ LANGUAGE sql SECURITY DEFINER SET search_path = public;

-- Allow admins full control over profiles
CREATE POLICY "Admins have full access to profiles" 
ON public.profiles FOR ALL TO authenticated 
USING ( public.is_admin() );

-- 5. RLS Policies for Activities
-- Allow anyone to see all activities
CREATE POLICY "Activities are viewable by everyone" 
ON public.activities FOR SELECT USING (true);

-- Allow only approved users or admins to post
CREATE POLICY "Approved users can create activities" 
ON public.activities FOR INSERT WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE id = auth.uid() 
        AND (status = 'approved' OR role = 'admin')
    )
);

-- Allow authors to delete their own activities
CREATE POLICY "Users can delete own activities" 
ON public.activities FOR DELETE USING (auth.uid() = author_id);

-- Allow admins to delete any activity (for content moderation)
CREATE POLICY "Admins can delete any activity" 
ON public.activities FOR DELETE TO authenticated 
USING ( public.is_admin() );

-- 6. Trigger for Auto-Profile Creation
-- This ensures that every time a user signs up in Auth, a corresponding row is created in public.profiles.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, username, full_name, email, role, status, avatar_url)
  VALUES (
      new.id, 
      COALESCE(new.raw_user_meta_data->>'username', 'User_' || substr(new.id::text, 1, 5)), 
      COALESCE(new.raw_user_meta_data->>'full_name', 'Oasis Member'), 
      new.email,
      COALESCE(new.raw_user_meta_data->>'role', 'community'),
      CASE WHEN (new.raw_user_meta_data->>'role' = 'admin') THEN 'approved' ELSE 'pending' END,
      COALESCE(new.raw_user_meta_data->>'avatar_url', 'assets/images/hero/logo.png')
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Cleanup existing trigger if it exists to avoid errors
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 7. MANUAL SYNC FOR EXISTING USERS (Run this if profiles are missing)
-- This finds anyone in auth.users who is NOT in public.profiles and adds them.
INSERT INTO public.profiles (id, username, full_name, email, role, status)
SELECT 
    id, 
    COALESCE(raw_user_meta_data->>'username', 'Member_' || substr(id::text, 1, 5)), 
    COALESCE(raw_user_meta_data->>'full_name', 'Oasis Member'), 
    email, 
    'community', 
    'pending'
FROM auth.users
WHERE id NOT IN (SELECT id FROM public.profiles)
ON CONFLICT (id) DO NOTHING;

-- 8. Create Audit Logs Table
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id UUID REFERENCES public.profiles(id) NOT NULL,
    action TEXT NOT NULL,
    target_user TEXT NOT NULL,
    details TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for Audit Logs
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Admins can see all audit logs
CREATE POLICY "Admins can view all audit logs" 
ON public.audit_logs FOR SELECT TO authenticated 
USING ( public.is_admin() );

-- Admins can insert audit logs
CREATE POLICY "Admins can insert audit logs" 
ON public.audit_logs FOR INSERT TO authenticated 
WITH CHECK ( public.is_admin() );

-- 9. Realtime Setup
-- To enable Realtime for your tables, run these commands in the SQL Editor:
-- ALTER PUBLICATION supabase_realtime ADD TABLE profiles;
-- ALTER PUBLICATION supabase_realtime ADD TABLE activities;
-- ALTER PUBLICATION supabase_realtime ADD TABLE audit_logs;
