-- 1. Create Stories Table for long-form news
CREATE TABLE IF NOT EXISTS public.stories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    summary TEXT NOT NULL,
    content TEXT NOT NULL,
    image_url TEXT,
    category TEXT DEFAULT 'General',
    author_id UUID REFERENCES public.profiles(id) DEFAULT auth.uid(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable RLS
ALTER TABLE public.stories ENABLE ROW LEVEL SECURITY;

-- 3. Policies
CREATE POLICY "Stories are viewable by everyone" 
ON public.stories FOR SELECT USING (true);

CREATE POLICY "Only admins can manage stories" 
ON public.stories FOR ALL TO authenticated 
USING ( public.is_admin() )
WITH CHECK ( public.is_admin() );

-- 4. Sample Data (Expanded Content)
-- 4. Sample Data (Complete set matching Program Cards)
TRUNCATE public.stories RESTART IDENTITY;

INSERT INTO public.stories (title, summary, content, image_url, category)
VALUES 
(
    'Maternity & 24h Emergency: A Lifeline for Mothers', 
    'Our dedicated maternity wing provides round-the-clock emergency medical response and comprehensive neonatal care to mothers in Isiolo.',
    'At Oasis of Hope, we believe that no mother should fear for her life or her child''s life during childbirth. Our 24-hour Emergency and Maternity department in Bulapesa represents our commitment to reducing maternal and neonatal mortality in Northern Kenya. 

The facility is equipped with modern delivery rooms, a specialized newborn unit, and a high-dependency ward for post-operative care. But equipment is only half the story. Our team of skilled midwifes, obstetricians, and pediatric nurses work in shifts to ensure that someone is always ready to respond, whether it''s a routine delivery at 2 PM or a complex emergency at 2 AM.

We also operate a dedicated medical transport system to bring mothers from remote settlements to the hub when they go into labor. This "last-mile" connectivity is what saves lives in the vast terrain of Isiolo County. Since we expanded this service, we have seen a significant increase in the number of facility-based deliveries, which is the most critical factor in ensuring safe outcomes for both mother and child. Your support helps us keep the lights on and the oxygen flowing 24 hours a day, 7 days a week.',
    'assets/images/slideshow/maternity.jpg',
    'Healthcare'
),
(
    'Borehole Projects: Sustaining Life Through Clean Water', 
    'Our solar-powered borehole systems currently serve over 200+ households with clean, safe, and reliable water in solar-powered systems.',
    'Water scarcity is one of the most significant challenges in Northern Kenya, affecting every aspect of life from health to education. The Oasis of Hope Borehole Project is designed to provide a permanent, sustainable solution to this crisis. 

Using solar-powered pumping technology, we tap into deep underground aquifers to provide a consistent supply of clean water even during the harshest droughts. Our systems are designed to be environment-friendly and low-maintenance, ensuring that the community isn''t burdened by high energy costs.

Each water point is managed by a local Water Users Association (WUA), which we train in governance, financial transparency, and basic technical repairs. This community-led model ensures that the water continues to flow long after the initial installation is complete. Currently, our primary borehole in the Bulapesa area serves over 200 households directly, while also providing a water trough for livestock—the primary livelihood for many in the region. By bringing water closer to home, we are reclaiming time for women and health for children, proving that a single well can transform a thousand lives.',
    'assets/images/slideshow/borehole.jpg',
    'WASH'
),
(
    'Vocational Training: Pathways to Economic Independence', 
    'Over 265+ women have been trained in tailoring and entrepreneurship, supported by micro-lending schemes to launch local businesses.',
    'Economic stability is a health indicator. When families have a reliable income, they can afford nutritious food, school fees, and medical care. Our Vocational Training and Micro-lending program is specifically designed to empower women who have historically lacked access to formal education or employment.

In our training center, women undergo a six-month intensive course in vocational skills like high-end tailoring, beadwork, and textile design. Simultaneously, they participate in entrepreneurship workshops that cover bookkeeping, markting, and customer service. We don''t just teach them how to make a product; we teach them how to run a business.

Upon graduation, each participant receives a starter kit—including a professional sewing machine—and is eligible for a micro-loan to launch their enterprise. Many of our graduates have gone on to open thriving shops in Isiolo town, creating a ripple effect of wealth that supports their children and the wider community. To date, we have empowered over 265 women, transforming them from aid recipients into local entrepreneurs and community leaders.',
    'assets/images/slideshow/youthtraining.jpg',
    'Women Empowerment'
),
(
    'ICT & Life Skills: Equipping the Next Generation', 
    'Equipping youth with essential digital literacy through ICT classes and critical life skills for personal and professional success.',
    'In a rapidly changing world, digital literacy is no longer a luxury—it is a necessity. Our Youth ICT and Life Skills Training program bridges the "digital divide" for young people in Northern Kenya who would otherwise be left behind by the global economy.

Our digital lab provides hands-on training in computer basics, the Microsoft Office suite, graphic design, and internet research. For many of our students, this is the first time they have ever sat in front of a computer. Beyond the technical, we integrate a "Life Skills" curriculum that focuses on leadership, communication, and career planning.

We want our youth to be creators, not just consumers, of technology. We have seen our students use their new skills to apply for university, start small online ventures, and secure employment in the local government and NGO sectors. By investing in the digital potential of our youth, we are ensuring that the future of Isiolo is bright, connected, and driven by the people who live here.',
    'assets/images/slideshow/youths.jpg',
    'Youth Programs'
),
(
    'Medical Camps: Bridging the Distance to Care', 
    'Direct community engagement serving 2,650+ patients through regular free medical camps and personalized home care visits.',
    'Not everyone can make the journey to our central clinic. For the elderly, those with severe disabilities, and families in remote settlements, the distance to healthcare can be an insurmountable barrier. That''s why Oasis of Hope goes to them.

Our Mobile Medical Camps and Home Visit programs are the "outreach arms" of our ministry. Once a month, our team loads an ambulance with medicines, diagnostic kits, and specialized staff to set up a temporary clinic in a distant village. In a single day, we can treat hundreds of patients for everything from malaria and upper respiratory infections to eye conditions and dental issues.

Between camps, our community health workers perform home visits to monitor chronic care patients and provide palliative care for the elderly. We also use these opportunities for public health education on nutrition and hygiene. To date, we have served over 2,650 patients through these outreach efforts, ensuring that no one is forgotten simply because they live off the beaten path.',
    'assets/images/slideshow/medicalcamp.jpg',
    'Community Outreach'
),
(
    'The Bulapesa Hub: Chronic Care and Primary Health', 
    'Operating a Level 2 dispensary for primary care and specialized long-term management for chronic illness patients.',
    'The Bulapesa Dispensary is the heartbeat of our medical mission. As a Level 2 facility, it serves as the first point of contact for thousands of residents seeking primary healthcare, immunizations, and pharmacy services.

One of our most critical focuses is the management of non-communicable diseases (NCDs) like hypertension and diabetes. In Northern Kenya, these "silent killers" often go undiagnosed until it is too late. Our chronic care clinic provides regular screening, subsidized medication, and lifestyle counseling to help hundreds of patients manage their conditions and lead full, productive lives.

The hub also houses our central laboratory and a community pharmacy that ensures life-saving drugs are always in stock. By providing consistent, high-quality primary care in a community setting, we reduce the burden on major referral hospitals and catch health issues before they become emergencies. The "Hub" model is about more than just medicine; it''s about building a trusted health home for the people of Bulapesa.',
    'assets/images/slideshow/tank.jpg',
    'Healthcare'
);
