-- Enhanced Social Features for Oasis Network

-- 1. Support for Multiple Media Items per Post
CREATE TABLE IF NOT EXISTS public.post_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES public.activities(id) ON DELETE CASCADE NOT NULL,
    url TEXT NOT NULL,
    type TEXT DEFAULT 'image' CHECK (type IN ('image', 'video')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.post_media ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Post media viewable by everyone" ON public.post_media FOR SELECT USING (true);
CREATE POLICY "Authors can manage post media" ON public.post_media FOR ALL TO authenticated 
USING (EXISTS (SELECT 1 FROM public.activities WHERE id = post_id AND author_id = auth.uid()));

-- 2. Reactions System for Posts
CREATE TABLE IF NOT EXISTS public.post_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES public.activities(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    reaction_type TEXT DEFAULT '👍' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(post_id, user_id)
);

ALTER TABLE public.post_reactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Reactions viewable by everyone" ON public.post_reactions FOR SELECT USING (true);
CREATE POLICY "Users can manage own post reactions" ON public.post_reactions FOR ALL TO authenticated USING (auth.uid() = user_id);

-- 3. Reactions System for Comments
CREATE TABLE IF NOT EXISTS public.comment_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id BIGINT REFERENCES public.comments(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    reaction_type TEXT DEFAULT '👍' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(comment_id, user_id)
);

ALTER TABLE public.comment_reactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Comment reactions viewable by everyone" ON public.comment_reactions FOR SELECT USING (true);
CREATE POLICY "Users can manage own comment reactions" ON public.comment_reactions FOR ALL TO authenticated USING (auth.uid() = user_id);

-- 4. Media in Comments
CREATE TABLE IF NOT EXISTS public.comment_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id BIGINT REFERENCES public.comments(id) ON DELETE CASCADE NOT NULL,
    url TEXT NOT NULL,
    type TEXT DEFAULT 'image' CHECK (type IN ('image', 'video', 'gif', 'sticker')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.comment_media ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Comment media viewable by everyone" ON public.comment_media FOR SELECT USING (true);

-- 5. Reporting System
CREATE TABLE IF NOT EXISTS public.reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    content_type TEXT NOT NULL CHECK (content_type IN ('post', 'comment')),
    content_id BIGINT NOT NULL,
    reason TEXT NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'resolved', 'dismissed')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can insert reports" ON public.reports FOR INSERT WITH CHECK (auth.uid() = reporter_id);
CREATE POLICY "Admins can view reports" ON public.reports FOR SELECT TO authenticated USING (public.is_admin());

-- 6. Moderation: Pinning Posts
ALTER TABLE public.activities ADD COLUMN IF NOT EXISTS is_pinned BOOLEAN DEFAULT FALSE;
ALTER TABLE public.activities ADD COLUMN IF NOT EXISTS is_hidden BOOLEAN DEFAULT FALSE;

-- 7. Moderation: Pinning Comments
ALTER TABLE public.comments ADD COLUMN IF NOT EXISTS is_pinned BOOLEAN DEFAULT FALSE;

-- 8. RPC for efficient reactions count
CREATE OR REPLACE FUNCTION public.get_post_reaction_stats(p_id BIGINT)
RETURNS TABLE(type TEXT, count BIGINT) AS $$
    SELECT reaction_type, count(*)
    FROM public.post_reactions
    WHERE post_id = p_id
    GROUP BY reaction_type;
$$ LANGUAGE sql STABLE;

CREATE OR REPLACE FUNCTION public.get_comment_reaction_stats(c_id BIGINT)
RETURNS TABLE(type TEXT, count BIGINT) AS $$
    SELECT reaction_type, count(*)
    FROM public.comment_reactions
    WHERE comment_id = c_id
    GROUP BY reaction_type;
$$ LANGUAGE sql STABLE;

-- 9. Add metadata for mentions/tags support (text processing is enough, but maybe a join table for easy lookup)
CREATE TABLE IF NOT EXISTS public.mentions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type TEXT NOT NULL CHECK (content_type IN ('post', 'comment')),
    content_id BIGINT NOT NULL,
    mentioned_user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.mentions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Mentions viewable by everyone" ON public.mentions FOR SELECT USING (true);

-- 10. Enable Realtime for New Tables
-- Run these manually in Supabase SQL editor:
-- ALTER PUBLICATION supabase_realtime ADD TABLE post_media;
-- ALTER PUBLICATION supabase_realtime ADD TABLE post_reactions;
-- ALTER PUBLICATION supabase_realtime ADD TABLE comment_reactions;
-- ALTER PUBLICATION supabase_realtime ADD TABLE comment_media;
-- ALTER PUBLICATION supabase_realtime ADD TABLE comments;
