-- 1. Create Comments Table
CREATE TABLE IF NOT EXISTS public.comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES public.activities(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    parent_id BIGINT REFERENCES public.comments(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    likes_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Add comments_count to activities if it doesn't exist
ALTER TABLE public.activities ADD COLUMN IF NOT EXISTS comments_count INTEGER DEFAULT 0;

-- 3. Enable RLS on Comments
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies
CREATE POLICY "Comments are viewable by everyone" 
ON public.comments FOR SELECT USING (true);

CREATE POLICY "Approved users can post comments" 
ON public.comments FOR INSERT WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.profiles 
        WHERE id = auth.uid() 
        AND (status = 'approved' OR role = 'admin')
    )
);

CREATE POLICY "Users can delete own comments" 
ON public.comments FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Admins can delete any comment" 
ON public.comments FOR DELETE TO authenticated 
USING ( public.is_admin() );

-- 5. RPC Functions for Atomic Increments
CREATE OR REPLACE FUNCTION public.increment_comment_count(activity_id BIGINT)
RETURNS void AS $$
BEGIN
  UPDATE public.activities
  SET comments_count = comments_count + 1
  WHERE id = activity_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.increment_comment_likes(comment_id BIGINT)
RETURNS void AS $$
BEGIN
  UPDATE public.comments
  SET likes_count = likes_count + 1
  WHERE id = comment_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
