-- 1. Create Notifications Table
CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    message TEXT NOT NULL,
    read BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable RLS on Notifications
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- 3. RLS Policies for Notifications
CREATE POLICY "Users can view own notifications"
ON public.notifications FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can update own notifications (mark as read)"
ON public.notifications FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "System/Admins can insert notifications"
ON public.notifications FOR INSERT WITH CHECK (true);

-- 4. Robust RLS for Profiles
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;

CREATE POLICY "Users can update own profile fields"
ON public.profiles FOR UPDATE 
USING (auth.uid() = id)
WITH CHECK (
    auth.uid() = id AND 
    (
        CASE 
            WHEN (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin' THEN true
            ELSE (
                (role IS NOT DISTINCT FROM (SELECT role FROM public.profiles WHERE id = auth.uid())) AND
                (status IS NOT DISTINCT FROM (SELECT status FROM public.profiles WHERE id = auth.uid()))
            )
        END
    )
);

-- 5. Enhanced RLS for Activities
DROP POLICY IF EXISTS "Users can delete own activities" ON public.activities;

CREATE POLICY "Authors or admins can delete activities"
ON public.activities FOR DELETE 
USING (auth.uid() = author_id OR public.is_admin());

-- 6. Triggers for Notifications
CREATE OR REPLACE FUNCTION public.notify_user_approval()
RETURNS trigger AS $$
BEGIN
  IF (OLD.status = 'pending' AND NEW.status = 'approved') THEN
    INSERT INTO public.notifications (user_id, message)
    VALUES (NEW.id, 'Congratulations! Your account has been approved. You can now post in the community.');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_user_approval
  AFTER UPDATE ON public.profiles
  FOR EACH ROW
  WHEN (OLD.status IS DISTINCT FROM NEW.status)
  EXECUTE FUNCTION public.notify_user_approval();

CREATE OR REPLACE FUNCTION public.notify_post_deletion()
RETURNS trigger AS $$
BEGIN
  IF (auth.uid() IS DISTINCT FROM OLD.author_id) THEN
    INSERT INTO public.notifications (user_id, message)
    VALUES (OLD.author_id, 'Your post was removed by a moderator for violating community guidelines.');
  END IF;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_post_deletion
  AFTER DELETE ON public.activities
  FOR EACH ROW
  EXECUTE FUNCTION public.notify_post_deletion();

-- 7. Performance Optimization: Indexes
CREATE INDEX IF NOT EXISTS idx_activities_created_at ON public.activities(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activities_author_id ON public.activities(author_id);
CREATE INDEX IF NOT EXISTS idx_profiles_username ON public.profiles(username);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_read ON public.notifications(read) WHERE read = false;

-- 8. Atomic Like Increment
CREATE OR REPLACE FUNCTION public.increment_likes(activity_id BIGINT)
RETURNS void AS $$
BEGIN
  UPDATE public.activities
  SET likes_count = likes_count + 1
  WHERE id = activity_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
